import { useUser } from '@supabase/auth-helpers-react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'

const Home: NextPage = () => {
  const [isLoaded, setIsLoaded] = useState(false)
  const user = useUser()
  useEffect(() => {
    setIsLoaded(true)
  }, [user])

  return (
    <>
      <Head>
        <title>Bannerfans</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}

export default Home

export const getServerSideProps = async () => {
  return {
    redirect: {
      permanent: false,
      destination: '/dashboard',
    },
    props: {},
  }
}
